services:
  backend:
    build: .
    env_file:
      - .env
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8000
    ports:
      - "8001:8000"

  frontend:
    build: .
    env_file:
      - .env
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "8502:8501"
    command:
      - streamlit
      - run
      - frontend/app.py
      - --server.address=0.0.0.0
      - --server.port=8501